theme: jekyll-theme-architect
title: Deepika R Prasad
description: Software Developer.
avatar: "/img/avatar-icon.jpg" 
LinkedIn: https://www.linkedin.com/in/deepika-r-prasad/
Gmail: deepika.grp@gmail.com
author: Deepika R Prasad
